# Generated by Django 3.2.25 on 2024-07-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeId', models.AutoField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
            ],
        ),
    ]
